{% set version = "1.1.61" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-x13binary
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/x13binary_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/x13binary/x13binary_{{ version }}.tar.gz
  sha256: 048ad8f3f281b20591dedc413688ce2d54f5e422aae726689ae4cf3ef0e3ec6c

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('x13binary')"           # [not win]
    - "\"%R%\" -e \"library('x13binary')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=x13binary
  license: GPL-2.0-or-later AND LicenseRef-X13AS
  summary: The US Census Bureau provides a seasonal adjustment program now called 'X-13ARIMA-SEATS' building on both earlier programs called X-11 and X-12 as well as the SEATS program by the Bank of Spain. The US Census Bureau offers both source and binary versions -- which this package integrates for use by other R packages.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE
    - inst/COPYRIGHT
    - inst/AUTHORS

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - ndmaxar
    - RyanHackney
    - conda-forge/r
    - oblute
